# Generated by Django 6.0 on 2025-12-24 11:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automate_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("scope", models.CharField(default="global", max_length=50)),
                ("max_tokens_per_day", models.IntegerField(default=100000)),
                (
                    "max_cost_per_day_usd",
                    models.DecimalField(decimal_places=4, default=10.0, max_digits=10),
                ),
                ("current_usage_tokens", models.IntegerField(default=0)),
                (
                    "current_usage_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("reset_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ConnectionProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("connector_slug", models.CharField(max_length=255)),
                ("environment", models.CharField(default="prod", max_length=50)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("encrypted_secrets", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField(blank=True, null=True)),
                (
                    "api_key_env_var",
                    models.CharField(default="OPENAI_API_KEY", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this MCP server", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'shopify-mcp')", unique=True
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        help_text="Base URL of the MCP server (e.g., http://localhost:3000)"
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "No Authentication"),
                            ("bearer", "Bearer Token"),
                            ("api_key", "API Key Header"),
                        ],
                        default="none",
                        help_text="How to authenticate with this server",
                        max_length=20,
                    ),
                ),
                (
                    "auth_secret_ref",
                    models.CharField(
                        blank=True,
                        help_text="Secret reference (e.g., 'env:MCP_SHOPIFY_TOKEN' or raw token)",
                        max_length=255,
                    ),
                ),
                (
                    "auth_header_name",
                    models.CharField(
                        default="Authorization",
                        help_text="Header name for API key auth (e.g., 'X-API-Key')",
                        max_length=100,
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "last_synced",
                    models.DateTimeField(
                        blank=True, help_text="Last time tools were synced", null=True
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last sync error if any"),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MCP Server",
                "verbose_name_plural": "MCP Servers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("slack_blocks", "Slack Blocks (JSON)"),
                            ("jinja", "Jinja2 Text"),
                            ("json", "JSON Payload"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Jinja2 supported. Use {{ event.payload.id }} etc."
                    ),
                ),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLMModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=1000)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automate.llmprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("locked", "Locked"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_owner", models.CharField(blank=True, max_length=255, null=True)),
                ("attempts", models.IntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_entry",
                        to="automate_core.event",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Outbox entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeadLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(db_index=True, default="unknown", max_length=50),
                ),
                ("last_error_redacted", models.TextField()),
                ("replay_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letter",
                        to="automate_core.execution",
                    ),
                ),
                (
                    "outbox",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letter",
                        to="automate.outbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("system_template", models.TextField(blank=True)),
                ("user_template", models.TextField()),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("output_schema", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_model_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default model to use for this prompt version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="automate.llmmodelconfig",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="automate.prompt",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("prompt", "version")},
            },
        ),
        migrations.CreateModel(
            name="MCPTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tool function name", max_length=100),
                ),
                ("description", models.TextField(help_text="What this tool does")),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="JSON Schema for tool parameters"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Can disable specific tools",
                    ),
                ),
                (
                    "call_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this tool was called"
                    ),
                ),
                ("last_called", models.DateTimeField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="automate.mcpserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Tool",
                "verbose_name_plural": "MCP Tools",
                "ordering": ["server", "name"],
                "unique_together": {("server", "name")},
            },
        ),
        migrations.CreateModel(
            name="PromptRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("dev", "Dev"),
                            ("staging", "Staging"),
                            ("prod", "Prod"),
                        ],
                        max_length=50,
                    ),
                ),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                ("deployed_by", models.CharField(max_length=255, null=True)),
                (
                    "model_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override model for this environment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="automate.llmmodelconfig",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automate.promptversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("prompt_version", "environment")},
            },
        ),
    ]
