# Generated by Django 6.0 on 2025-12-24 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outbox",
            name="event",
        ),
        migrations.DeleteModel(
            name="DeadLetter",
        ),
        migrations.DeleteModel(
            name="Outbox",
        ),
    ]
