# Generated by Django 6.0 on 2025-12-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0003_llmprovider_prompt_execution_executionstep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="execution",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
    ]
