# Generated by Django 6.0 on 2025-12-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0004_execution_attempts_execution_max_retries"),
    ]

    operations = [
        migrations.AddField(
            model_name="outbox",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="outbox",
            name="lock_owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="outbox",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outbox",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
