# Generated by Django 6.0 on 2025-12-21 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automate",
            "0005_outbox_attempts_outbox_lock_owner_outbox_locked_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(db_index=True, default="unknown", max_length=50),
                ),
                ("last_error_redacted", models.TextField()),
                ("replay_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letter",
                        to="automate.execution",
                    ),
                ),
            ],
        ),
    ]
