# Generated by Django 6.0 on 2025-12-21 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0006_deadletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("slack_blocks", "Slack Blocks (JSON)"),
                            ("jinja", "Jinja2 Text"),
                            ("json", "JSON Payload"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Jinja2 supported. Use {{ event.payload.id }} etc."
                    ),
                ),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
