# Generated by Django 6.0 on 2025-12-21 21:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0008_connectionprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("scope", models.CharField(default="global", max_length=50)),
                ("max_tokens_per_day", models.IntegerField(default=100000)),
                (
                    "max_cost_per_day_usd",
                    models.DecimalField(decimal_places=4, default=10.0, max_digits=10),
                ),
                ("current_usage_tokens", models.IntegerField(default=0)),
                (
                    "current_usage_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("reset_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="promptversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PromptRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("dev", "Dev"),
                            ("staging", "Staging"),
                            ("prod", "Prod"),
                        ],
                        max_length=50,
                    ),
                ),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                ("deployed_by", models.CharField(max_length=255, null=True)),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automate.promptversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("prompt_version", "environment")},
            },
        ),
    ]
