# Generated by Django 6.0 on 2025-12-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0009_budgetpolicy_promptversion_status_promptrelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadletter",
            name="outbox",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dead_letter",
                to="automate.outbox",
            ),
        ),
        migrations.AlterField(
            model_name="deadletter",
            name="execution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dead_letter",
                to="automate.execution",
            ),
        ),
        migrations.AlterField(
            model_name="outbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("locked", "Locked"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("dead", "Dead"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("idempotency_key",), name="unique_event_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.UniqueConstraint(
                fields=("event", "automation", "workflow_version"),
                name="unique_execution_dispatch",
            ),
        ),
    ]
