# Generated by Django 6.0 on 2025-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0010_deadletter_outbox_alter_deadletter_execution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionprofile",
            name="slug",
            field=models.SlugField(default="default-slug", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
