# Generated by Django 6.0 on 2025-12-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0011_connectionprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptrelease",
            name="model_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Override model for this environment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="automate.llmmodelconfig",
            ),
        ),
        migrations.AddField(
            model_name="promptversion",
            name="default_model_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Default model to use for this prompt version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="automate.llmmodelconfig",
            ),
        ),
    ]
