# Generated by Django 6.0 on 2025-12-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0012_promptrelease_model_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodelconfig",
            name="is_default",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
