# Generated by Django 6.0 on 2025-12-23 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0013_add_is_default_to_llmmodelconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this MCP server", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'shopify-mcp')", unique=True
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        help_text="Base URL of the MCP server (e.g., http://localhost:3000)"
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "No Authentication"),
                            ("bearer", "Bearer Token"),
                            ("api_key", "API Key Header"),
                        ],
                        default="none",
                        help_text="How to authenticate with this server",
                        max_length=20,
                    ),
                ),
                (
                    "auth_secret_ref",
                    models.CharField(
                        blank=True,
                        help_text="Secret reference (e.g., 'env:MCP_SHOPIFY_TOKEN' or raw token)",
                        max_length=255,
                    ),
                ),
                (
                    "auth_header_name",
                    models.CharField(
                        default="Authorization",
                        help_text="Header name for API key auth (e.g., 'X-API-Key')",
                        max_length=100,
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "last_synced",
                    models.DateTimeField(
                        blank=True, help_text="Last time tools were synced", null=True
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last sync error if any"),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MCP Server",
                "verbose_name_plural": "MCP Servers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MCPTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tool function name", max_length=100),
                ),
                ("description", models.TextField(help_text="What this tool does")),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="JSON Schema for tool parameters"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Can disable specific tools",
                    ),
                ),
                (
                    "call_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this tool was called"
                    ),
                ),
                ("last_called", models.DateTimeField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="automate.mcpserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Tool",
                "verbose_name_plural": "MCP Tools",
                "ordering": ["server", "name"],
                "unique_together": {("server", "name")},
            },
        ),
    ]
