# Generated by Django 6.0 on 2025-12-24 08:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", unique=True),
                ),
                (
                    "provider_key",
                    models.CharField(
                        choices=[
                            ("external_rag", "External RAG Service"),
                            ("django_model", "Django Model / DB Query"),
                            ("s3", "S3 / Cloud Storage"),
                            ("file_system", "Local File System"),
                        ],
                        default="external_rag",
                        help_text="Provider type that handles this source",
                        max_length=100,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific configuration (schema validated)",
                    ),
                ),
                (
                    "credentials_ref",
                    models.CharField(
                        blank=True,
                        help_text="SecretRef URI (e.g., env://API_KEY, vault://path/to/secret)",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("pending", "Pending Setup"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("owner_team", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_by", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Knowledge Source",
                "verbose_name_plural": "Knowledge Sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RAGEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(help_text="Used in API URL: /api/rag/{slug}/query", unique=True),
                ),
                (
                    "retrieval_provider_key",
                    models.CharField(
                        default="external_rag",
                        help_text="Provider that handles retrieval queries",
                        max_length=100,
                    ),
                ),
                (
                    "retrieval_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Retrieval settings: top_k, filters, rerank, etc.",
                    ),
                ),
                (
                    "access_policy",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="RBAC/ABAC rules: allowed groups, scopes, etc.",
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(default=100, help_text="Max queries per minute"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="rag.knowledgesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG Endpoint",
                "verbose_name_plural": "RAG Endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RAGQueryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Correlation ID for tracing",
                    ),
                ),
                ("user", models.CharField(db_index=True, max_length=150)),
                (
                    "query_hash",
                    models.CharField(help_text="SHA256 hash of query (for privacy)", max_length=64),
                ),
                (
                    "latency_ms",
                    models.IntegerField(help_text="Total query latency in ms"),
                ),
                (
                    "results_meta",
                    models.JSONField(default=dict, help_text="Metadata: doc_ids, scores, count"),
                ),
                (
                    "policy_decisions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Access control decisions made",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_logs",
                        to="rag.ragendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Log",
                "verbose_name_plural": "Query Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="rag_ragquer_endpoin_26b9a9_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="rag_ragquer_user_dc5498_idx",
                    ),
                ],
            },
        ),
    ]
