# Generated by Django 6.0 on 2025-12-24 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'openai-ada-002')",
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("azure_openai", "Azure OpenAI"),
                            ("huggingface", "HuggingFace (Local/API)"),
                        ],
                        default="openai",
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider config: model_name, api_base, dimensions, etc.",
                    ),
                ),
                (
                    "credentials_ref",
                    models.CharField(
                        blank=True,
                        help_text="API Key or secret reference",
                        max_length=500,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use this model if none specified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Embedding Model",
                "verbose_name_plural": "Embedding Models",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AlterField(
            model_name="knowledgesource",
            name="provider_key",
            field=models.CharField(
                choices=[
                    ("external_rag", "External RAG Service"),
                    ("local_index", "Local Index (Milvus/PGVector)"),
                    ("django_model", "Django Model / DB Query"),
                    ("s3", "S3 / Cloud Storage"),
                    ("file_system", "Local File System"),
                ],
                default="external_rag",
                help_text="Provider type that handles this source",
                max_length=100,
            ),
        ),
    ]
