# Generated by Django 6.0 on 2025-12-23 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("source", models.CharField(max_length=64)),
                ("trigger_id", models.IntegerField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("payload", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "occurred_at"],
                        name="automate_co_tenant__18f1ad_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "event_type", "occurred_at"],
                        name="automate_co_tenant__349baf_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("tenant_id", "idempotency_key"),
                        name="event_idempotency_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("RETRY", "Retry"),
                            ("DLQ", "Dead Letter Queue"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("priority", models.IntegerField(default=100)),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=15)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "lease_owner",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="automate_co_status_8f4463_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status", "next_attempt_at"],
                        name="automate_co_tenant__619804_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("tenant_id", "idempotency_key"),
                        name="outbox_idempotency_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TriggerSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("WEBHOOK", "Webhook"),
                            ("SCHEDULE", "Schedule"),
                            ("SIGNAL", "Signal"),
                            ("ADMIN_ACTION", "Admin Action"),
                        ],
                        max_length=32,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("tenant_id", "name")},
            },
        ),
    ]
