# Generated by Django 6.0 on 2025-12-24 11:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("slug", models.SlugField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active"],
                        name="automate_co_tenant__eaedd2_idx",
                    )
                ],
                "unique_together": {("tenant_id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("source", models.CharField(max_length=64)),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("trigger_id", models.IntegerField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("context", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("dispatched", "Dispatched"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "occurred_at"],
                        name="automate_co_tenant__18f1ad_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "event_type", "occurred_at"],
                        name="automate_co_tenant__349baf_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="automate_co_status_15a16c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("tenant_id", "source", "idempotency_key"),
                        name="event_idempotency_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("workflow_version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempt", models.IntegerField(default=1)),
                ("context", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="automate_core.automation",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="automate_core.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("RETRY", "Retry"),
                            ("DLQ", "Dead Letter Queue"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("priority", models.IntegerField(default=100)),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=15)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "lease_owner",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="automate_co_status_8f4463_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status", "next_attempt_at"],
                        name="automate_co_tenant__619804_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("tenant_id", "idempotency_key"),
                        name="outbox_idempotency_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("automation", "Automation"),
                            ("endpoint", "Endpoint"),
                            ("user", "User"),
                        ],
                        default="global",
                        max_length=32,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("rules", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "scope", "target_id"],
                        name="automate_co_tenant__5d20a2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RuleSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("conditions", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="automate_core.automation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_key", models.CharField(max_length=255)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attempt", models.IntegerField(default=1)),
                ("provider_meta", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="automate_core.execution",
                    ),
                ),
            ],
            options={
                "unique_together": {("execution", "node_key")},
            },
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("model_signal", "Model Signal"),
                            ("webhook", "Webhook"),
                            ("schedule", "Schedule"),
                            ("manual", "Manual"),
                            ("external", "External"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type pattern to match (e.g. order.*)",
                        max_length=255,
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(
                        default=dict, help_text="JSONLogic/filtering rules"
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="automate_core.automation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="execution",
            name="trigger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="automate_core.trigger",
            ),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("graph", models.JSONField(default=dict)),
                ("hash", models.CharField(editable=False, max_length=64)),
                ("is_live", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="automate_core.automation",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("json", "JSON"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("file", "File"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "uri",
                    models.CharField(help_text="s3:// or file:// URI", max_length=1024),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream", max_length=128
                    ),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("meta", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="automate_core.execution",
                    ),
                ),
                (
                    "step_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="automate_core.steprun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "execution"],
                        name="automate_co_tenant__9efd6d_idx",
                    ),
                    models.Index(
                        fields=["sha256"], name="automate_co_sha256_01fd0f_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="trigger",
            index=models.Index(
                fields=["type", "event_type"], name="automate_co_type_40fb60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["tenant_id", "status"], name="automate_co_tenant__1ef932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["status", "started_at"], name="automate_co_status_09ca17_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "automation", "event"),
                name="unique_execution_per_event",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflow",
            unique_together={("automation", "version")},
        ),
    ]
