# Generated by Django 6.0 on 2025-12-24 11:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automate_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SideEffectLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("external_id", models.CharField(max_length=255)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="execution",
            name="automate_co_status_09ca17_idx",
        ),
        migrations.AddField(
            model_name="execution",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="lease_owner",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="execution",
            name="priority",
            field=models.IntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name="steprun",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="steprun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="steprun",
            name="lease_owner",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["status", "lease_expires_at"],
                name="automate_co_status_f0f507_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="steprun",
            index=models.Index(
                fields=["status", "lease_expires_at"],
                name="automate_co_status_1a9012_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sideeffectlog",
            index=models.Index(fields=["tenant_id", "key"], name="automate_co_tenant__c87b0d_idx"),
        ),
    ]
