# Generated by Django 6.0 on 2025-12-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate_core", "0002_sideeffectlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="error_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
