# Generated by Django 6.0 on 2025-12-24 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate_core", "0003_execution_error_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("execution", "Execution"),
                            ("step", "Step"),
                            ("modal", "Modal Call"),
                            ("rag", "RAG Operation"),
                            ("connector", "Connector Sync"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="e.g. execution.run, step.run", max_length=255
                    ),
                ),
                (
                    "payload_redacted",
                    models.JSONField(
                        default=dict, help_text="Redacted payload for execution"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retry_scheduled", "Retry Scheduled"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("dlq", "Dead Letter Queue"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=50,
                    ),
                ),
                ("queue_name", models.CharField(default="default", max_length=100)),
                (
                    "priority",
                    models.IntegerField(
                        default=10, help_text="Lower is higher priority (1-100)"
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("celery", "Celery"),
                            ("outbox-db", "DB Outbox"),
                            ("rq", "Redis Queue"),
                            ("sqs", "SQS Direct"),
                        ],
                        default="celery",
                        max_length=50,
                    ),
                ),
                (
                    "backend_task_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Celery Task ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "backend_message_id",
                    models.CharField(
                        blank=True,
                        help_text="SQS/Rabbit Message ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "lease_owner",
                    models.CharField(
                        blank=True,
                        help_text="Worker ID owning this job",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_redacted", models.JSONField(blank=True, default=dict)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="automate_co_status_fbdd6d_idx",
                    ),
                    models.Index(
                        fields=["lease_expires_at"],
                        name="automate_co_lease_e_90aeb9_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="automate_co_correla_681b5b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seq",
                    models.IntegerField(
                        help_text="Monotonic sequence number for this job"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("progress", "Progress"),
                            ("log", "Log"),
                            ("artifact", "Artifact"),
                            ("final", "Final Status"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="automate_core.job",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "seq"],
                "unique_together": {("job", "seq")},
            },
        ),
    ]
