# Generated by Django 6.0 on 2025-12-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate_core", "0004_job_jobevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_seq",
            field=models.IntegerField(
                default=0, help_text="Last event sequence number for this job"
            ),
        ),
    ]
