# Generated by Django 6.0 on 2025-12-23 08:15

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThrottleBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("tokens", models.FloatField(default=0.0)),
                ("last_refill", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConnectionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("config", models.JSONField(default=dict)),
                ("secrets", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "unique_together": {("tenant_id", "kind", "name")},
            },
        ),
        migrations.CreateModel(
            name="RuleSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("rule_json", models.JSONField(default=dict)),
                ("index_terms", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "enabled", "priority"],
                        name="automate_go_tenant__9191db_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(fields=["index_terms"], name="rule_terms_gin"),
                ],
                "unique_together": {("tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="StoredSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("ciphertext", models.BinaryField()),
                ("version", models.IntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["namespace", "name", "is_current"],
                        name="automate_go_namespa_9565d0_idx",
                    )
                ],
                "unique_together": {("namespace", "name", "version")},
            },
        ),
    ]
