# Generated by Django 6.0 on 2025-12-23 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automate_governance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rulespec",
            name="rule_terms_gin",
        ),
    ]
