# Generated by Django 6.0 on 2025-12-24 19:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate_governance", "0002_remove_rulespec_rule_terms_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=50)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.JSONField(
                        default=dict,
                        help_text="{'type': 'user|token|system', 'id': '...', 'name': '...'}",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, help_text="e.g. endpoint.run", max_length=100
                    ),
                ),
                (
                    "resource",
                    models.JSONField(
                        default=dict, help_text="{'type': '...', 'id': '...'}"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("denied", "Denied"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("payload_redacted", models.JSONField(default=dict)),
                ("hash", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.DeleteModel(
            name="ConnectionProfile",
        ),
        migrations.AlterUniqueTogether(
            name="rulespec",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="rulespec",
            name="automate_go_tenant__9191db_idx",
        ),
        migrations.DeleteModel(
            name="RuleSpec",
        ),
        migrations.AlterUniqueTogether(
            name="storedsecret",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="storedsecret",
            name="automate_go_namespa_9565d0_idx",
        ),
        migrations.DeleteModel(
            name="StoredSecret",
        ),
        migrations.DeleteModel(
            name="ThrottleBucket",
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "occurred_at"], name="automate_go_action_e194a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor"], name="automate_go_actor_d40a27_idx"),
        ),
    ]
