# Generated by Django 6.0 on 2025-12-23 18:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate_datachat", "0001_add_chat_session_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatEmbed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this embed config", max_length=100
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        editable=False,
                        help_text="API key for authenticating embed requests",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "allowed_domains",
                    models.JSONField(
                        default=list,
                        help_text='List of allowed domains ["example.com", "*.myapp.io"]',
                    ),
                ),
                (
                    "require_auth",
                    models.BooleanField(
                        default=False,
                        help_text="Require user login (redirects to your auth)",
                    ),
                ),
                (
                    "allowed_tables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Restrict to specific tables (empty = all)",
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(
                        default=10, help_text="Max requests per minute per session"
                    ),
                ),
                (
                    "max_queries_per_session",
                    models.IntegerField(
                        default=100, help_text="Max total queries per session"
                    ),
                ),
                (
                    "theme",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"primaryColor": "#2563eb", "title": "Data Assistant"}',
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="Hello! Ask me anything about your data.",
                        help_text="Initial message shown in the widget",
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Embed",
                "verbose_name_plural": "Chat Embeds",
                "ordering": ["-created_at"],
            },
        ),
    ]
