# Generated by Django 6.0 on 2025-12-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=128)),
                ("input_tokens", models.IntegerField(null=True)),
                ("output_tokens", models.IntegerField(null=True)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, max_digits=12, null=True),
                ),
                ("latency_ms", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "created_at"],
                        name="automate_ll_tenant__382f18_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("version", models.IntegerField(default=1)),
                ("template_text", models.TextField()),
                ("input_schema", models.JSONField(default=dict)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "name", "is_active"],
                        name="automate_ll_tenant__fd9cdc_idx",
                    )
                ],
                "unique_together": {("tenant_id", "name", "version")},
            },
        ),
    ]
