# Generated by Django 6.0 on 2025-12-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automate_llm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="prompt_slug",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="purpose",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="llmrequest",
            name="tenant_id",
            field=models.CharField(db_index=True, default="default", max_length=64),
        ),
        migrations.AddIndex(
            model_name="llmrequest",
            index=models.Index(fields=["purpose", "created_at"], name="automate_ll_purpose_36db76_idx"),
        ),
    ]
