# Generated by Django 6.0 on 2025-12-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate_llm", "0002_add_llmrequest_context_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="input_payload",
            field=models.JSONField(
                blank=True, help_text="Messages sent to LLM", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="output_content",
            field=models.TextField(blank=True, help_text="Raw LLM response text"),
        ),
    ]
