# Generated by Django 6.0 on 2025-12-25 07:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate_llm", "0003_add_io_payload_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                (
                    "job_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("step_run_id", models.CharField(blank=True, max_length=64, null=True)),
                ("provider_key", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=128)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("cache_hit_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("pricing_version", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable key e.g. invoice.extract.v1", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromptRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(db_index=True, default="prod", max_length=50),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "released_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("released", "Released"),
                            ("deprecated", "Deprecated"),
                            ("revoked", "Revoked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "system_template",
                    models.TextField(
                        blank=True, help_text="Jinja2 system message template"
                    ),
                ),
                (
                    "user_template",
                    models.TextField(
                        blank=True, help_text="Jinja2 user message template"
                    ),
                ),
                ("few_shots", models.JSONField(blank=True, default=list)),
                ("variables_schema", models.JSONField(blank=True, default=dict)),
                ("output_schema", models.JSONField(blank=True, default=dict)),
                ("tool_policy", models.JSONField(blank=True, default=dict)),
                ("model_defaults", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("change_log", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="prompttemplate",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="prompttemplate",
            name="automate_ll_tenant__fd9cdc_idx",
        ),
        migrations.DeleteModel(
            name="PromptTemplate",
        ),
        migrations.AddIndex(
            model_name="llmusage",
            index=models.Index(
                fields=["tenant_id", "created_at"],
                name="automate_ll_tenant__800d26_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("tenant_id", "key")},
        ),
        migrations.AddField(
            model_name="promptrelease",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releases",
                to="automate_llm.prompt",
            ),
        ),
        migrations.AddField(
            model_name="promptversion",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="automate_llm.prompt",
            ),
        ),
        migrations.AddField(
            model_name="promptrelease",
            name="active_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="automate_llm.promptversion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promptversion",
            unique_together={("prompt", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="promptrelease",
            unique_together={("prompt", "channel")},
        ),
    ]
