# Generated by Django 6.0 on 2025-12-25 07:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corpus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "default_rag_policy_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Corpora",
                "unique_together": {("tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("local_upload", "Local Upload"),
                            ("artifact", "Artifact"),
                            ("url", "URL Scrape"),
                            ("microservice", "Microservice (BYO)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="automate_rag.corpus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "external_ref",
                    models.CharField(
                        blank=True, help_text="URL, File Path, ID", max_length=1024
                    ),
                ),
                (
                    "content_artifact_id",
                    models.CharField(
                        blank=True,
                        help_text="Pointer to raw content in Artifact Store",
                        max_length=255,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("parsed", "Parsed"),
                            ("chunked", "Chunked"),
                            ("embedded", "Embedded"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="automate_rag.corpus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="automate_rag.knowledgesource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("chunk_index", models.PositiveIntegerField()),
                ("text_artifact_id", models.CharField(blank=True, max_length=255)),
                ("text_preview", models.CharField(blank=True, max_length=512)),
                ("token_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="automate_rag.corpus",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="automate_rag.document",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
                "unique_together": {("document", "chunk_index")},
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant_id", "corpus", "status"],
                name="automate_ra_tenant__db1234_idx",
            ),
        ),
    ]
