# Generated by Django 6.0 on 2025-12-24 09:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModalAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=100, null=True)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModalEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug for this endpoint (e.g. 'company-chat')",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "allowed_task_types",
                    models.JSONField(default=list, help_text="List of allowed ModalTaskType strings"),
                ),
                (
                    "default_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default parameters injected into requests (e.g. model='gpt-4', voice_id='...')",
                    ),
                ),
                (
                    "access_policy",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="RBAC policy: allowed_groups, allowed_users, etc.",
                    ),
                ),
                ("rate_limit", models.JSONField(blank=True, default=dict)),
                ("budget_policy", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModalProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "provider_key",
                    models.CharField(help_text="Key from the ProviderRegistry", max_length=100),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON config matching provider schema. Secrets should use SecretRef (env://...)",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModalJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_id",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                ("task_type", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("dlq", "Dead Letter Queue"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("payload_redacted", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_redacted", models.TextField(blank=True)),
                ("worker_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="automate_modal.modalendpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModalArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=50)),
                ("uri", models.CharField(max_length=1024)),
                ("mime", models.CharField(max_length=100)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="automate_modal.modaljob",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="modalendpoint",
            name="provider_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="automate_modal.modalproviderconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="modaljob",
            index=models.Index(fields=["state", "scheduled_at"], name="automate_mo_state_57cc9e_idx"),
        ),
    ]
